Feature/consolidation yggdrasil artifacts
HyperAgents/jacamo-hypermedia pull request #1
Opened 2024-06-19 10:07 UTC by V4L3

2024-06-20 10:42 UTC, andreiciortea requested changes
Many thanks, @V4L3!

2024-06-20 10:42 UTC, andreiciortea commented on lib/src/main/java/org/hyperagents/jacamo/artifacts/yggdrasil/NotificationServerArtifact.java
> +                /**
We should clean up this part

2024-06-20 10:42 UTC, andreiciortea commented on lib/src/main/java/org/hyperagents/jacamo/artifacts/yggdrasil/NotificationServerArtifact.java
> +/**
We should document all operations exposed to agents

2024-06-20 10:42 UTC, andreiciortea commented on lib/src/main/java/org/hyperagents/jacamo/artifacts/yggdrasil/Notification.java
> +public class Notification {
We should document this class as well

2024-06-20 10:42 UTC, andreiciortea commented on lib/src/main/java/org/hyperagents/jacamo/artifacts/yggdrasil/YggdrasilThingArtifact.java
> +     * Registers for WebSub to an Yggdrasil node. This is not a generic
Ideally, we should improve the implementation such that it is no longer specific to Yggdrasil — but works for any ThingArtifact using WebSub.

2024-06-21 10:15 UTC, V4L3 commented
@andreiciortea , thanks for the feedback.
I have made some adjustments:
- Added documentation
- Renamed YggdrasilThingArtifact to WebSubThingArtifact and moved it to the `wot` package
- Generalized the WebSub implementation to handle multiple cases: 2 Link headers, 1 Link header, Link tags in HTML
- Moved HMAS class to its own package
- Some Clean up
- Added an Example and adjusted the ReadMe.md

2024-06-24 10:22 UTC, andreiciortea approved these changes

2024-06-24 10:31 UTC, andreiciortea approved these changes
Great, thanks @V4L3 !

2024-06-24 10:38 UTC, merged